name: langchain_app1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - aiohttp=3.8.4=py39h72bdee0_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - altair=4.2.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow-cpp=11.0.0=py39h613000e_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - boost-cpp=1.82.0=he19a28c_1
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39he91dace_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - cryptography=38.0.4=py39hd97740a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - debugpy=1.6.7=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fonttools=4.39.3=py39h72bdee0_0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.3.3=py39hb9d737c_0
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glog=0.5.0=h48cff8f_0
  - gptcache=0.1.19=pyhd8ed1ab_0
  - greenlet=2.0.2=py39h227be39_0
  - grpc-cpp=1.46.1=h33aed49_1
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.22.0=pyh210e3f2_0
  - ipython=8.12.1=pyh41d4057_0
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hf3d152e_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.19.3=h3790be6_0
  - langchain=0.0.149=pyhd8ed1ab_1
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.20.3=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libthrift=0.15.0=he6d91bd_1
  - libtiff=4.5.0=ha587672_6
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib-base=3.7.1=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - multidict=6.0.4=py39h72bdee0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.8.4=py39h5ef5dce_100
  - numpy=1.24.3=py39h6183b62_0
  - openai=0.27.4=pyhd8ed1ab_0
  - openapi-schema-pydantic=1.2.4=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openpyxl=3.1.2=py39hd1e30aa_0
  - openssl=1.1.1t=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ad29b5_1
  - pandas-stubs=2.0.0.230412=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py39h7207d5c_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.0=pyhd8ed1ab_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=3.20.3=py39h227be39_1
  - psutil=5.9.5=py39h72bdee0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py39h992f0b0_0
  - pycodestyle=2.10.0=py39h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.7=py39h72bdee0_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pympler=1.0.1=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py39hf3d152e_3
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.2=py39h0be026e_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h8228510_1
  - requests=2.29.0=pyhd8ed1ab_0
  - rich=13.3.5=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py39hd189fd4_1
  - scipy=1.10.1=py39he83f1e1_0
  - sentry-sdk=1.21.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=2.0.11=py39hd1e30aa_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.21.0=pyhd8ed1ab_1
  - stringcase=1.2.0=py_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3=py39h72bdee0_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - types-pytz=2023.3.0.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - typing_inspect=0.8.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - tzlocal=4.3=py39hf3d152e_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - utf8proc=2.6.1=h27cfd23_0
  - validators=0.20.0=pyhd8ed1ab_0
  - wandb=0.15.0=pyhd8ed1ab_0
  - watchdog=3.0.0=py39hf3d152e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - wikipedia=1.4.0=py_2
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.1=py39hd1e30aa_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
prefix: /home/bismayan/anaconda3/envs/langchain_app1
